// Code generated by go-bindata.
// sources:
// conf/app.yml
// conf/db.yml
// DO NOT EDIT!

package conf

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _confAppYml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x3c\x8f\x41\x6b\x1a\x41\x18\x86\xef\x0b\xfb\x1f\x3e\xf0\x26\xca\x8e\xa2\x76\x19\xe8\xa1\xb5\x5a\x2a\x5a\xa5\x5d\xe9\xa1\x94\x32\xee\x7e\xdd\x5d\xd8\x9d\x4f\x66\x66\xab\x3d\x17\x29\x85\x7a\xec\x21\x39\xe7\x92\x1c\x3c\x27\x24\xfe\x1b\x17\x93\x53\xfe\x42\x98\x18\xbd\x0c\xf3\xbe\xcf\xcb\xc3\xcc\xbb\x54\x8b\x59\x86\x13\x61\x92\x2e\x29\x85\xa1\x49\x49\x72\xf8\x21\x32\x8d\xae\xd3\x93\x47\xd8\xd3\xa1\x98\xe3\x09\xf4\x53\x85\x23\x34\x09\x45\x1f\xc9\xbc\xc9\x32\x5a\x60\x74\x82\x2f\xce\xb7\x14\xfd\xea\x92\xd4\x45\x3e\xb7\xd2\xb1\x9c\xca\x5c\x28\x9d\x88\xec\xb4\x0c\xd2\x1c\xfb\xa4\x72\x61\x38\x8c\x48\xd6\x80\x35\x60\x20\x24\x34\x19\xeb\x40\xa3\xcd\x59\x8b\xb3\x36\xbc\x1f\x05\xae\xd3\x4d\x84\xd2\x68\x38\x4c\x83\x7e\xdd\x77\x1d\xd7\xa9\xdc\xff\xb9\x2a\x37\xe7\xbb\x9b\xbf\x0f\xab\xf5\x7e\xbb\x71\x9d\xb1\x49\x50\x71\xd7\x01\x98\x90\x32\x1c\x7c\xe6\xfb\x36\x7d\x88\x25\x29\x9c\x7e\x1a\x6a\x0e\x5f\xbd\x1a\x78\x09\xe5\x58\x03\xaf\xd0\xa8\xbc\x8c\xe2\x54\x1e\x83\xc2\x38\xd5\xc6\xb2\xe7\xfa\xfb\x7c\x11\x7d\xb3\x86\xc1\x97\xc0\xbe\x95\x0a\xc3\xa1\xc3\x5a\x3e\x63\x50\xd1\x18\x92\x8c\x00\x3a\x0c\xaa\x87\xa3\xd9\x82\x2a\xbc\x82\xd7\xc7\xc9\xe3\xdd\xbf\xdd\xf5\xef\xf2\xe2\xb2\x5c\xad\xf7\x67\xb7\xe5\xf6\xbf\x75\x0d\x29\x1e\xe2\x4f\xcc\x38\x44\x38\x2b\x62\x5b\x7d\xc6\x50\xd9\xbf\x2d\x97\xcb\xfa\xe1\xee\x3a\x4f\x01\x00\x00\xff\xff\x3f\x14\x50\xed\x9a\x01\x00\x00")

func confAppYmlBytes() ([]byte, error) {
	return bindataRead(
		_confAppYml,
		"conf/app.yml",
	)
}

func confAppYml() (*asset, error) {
	bytes, err := confAppYmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "conf/app.yml", size: 410, mode: os.FileMode(438), modTime: time.Unix(1554779668, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _confDbYml = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xec\xd0\xb1\x4a\x03\x41\x10\xc6\xf1\xfe\x20\xef\x30\x90\xfe\xb8\x33\xa0\x32\xad\x95\x20\x58\xf8\x04\x73\x77\x93\xdc\xc1\xde\x6e\xb2\xb3\x97\xc4\x2e\x85\x8d\x8d\x16\x12\x04\x11\xb1\x88\x04\xbb\xd3\x52\x04\x9f\xe6\x36\xfa\x16\xb2\x87\x45\x1e\xc2\x72\x7f\xec\xff\x2b\xa6\x26\x71\x6c\x71\x10\x01\x14\x15\x29\xce\x1d\x42\x7d\x29\x33\x15\xa4\x11\xb6\x08\x39\x49\x56\xe9\xf0\x9e\x92\xc8\xc2\xd8\x02\xa1\xa6\x65\xa5\xc7\x26\x60\x69\xc4\x21\xa4\x07\x47\x71\x12\x27\x71\xda\xff\x33\xd6\x21\x8c\x46\xc9\x61\xbf\x4b\x8e\x32\x12\xde\x5f\xca\x4b\xb2\xc2\x0e\xa1\x71\xe3\xe3\x00\x52\x9a\xc5\xc5\x4c\x21\x38\xdb\x70\x00\x65\x26\x67\x3c\x67\x85\x50\x70\xd6\x4c\x02\xd5\xb4\x3c\x2d\x14\x9f\x18\xad\x05\x21\x4d\x60\x08\xdf\x5f\x4f\xfe\xe6\xc5\xbf\x3d\xef\x1e\xae\x76\xaf\x1f\x3f\xf7\xef\x7e\xdd\x76\x9b\x6d\xd7\xde\x0e\xa2\x61\x9f\x9c\x4f\x59\xef\x27\xfe\x71\xd5\x6d\xb6\xfe\xfa\xae\xfb\x5c\xfd\xe5\xeb\x76\x10\x89\xa2\x39\xff\xdf\x21\xfa\x0d\x00\x00\xff\xff\xe0\xb0\x3d\x95\x11\x02\x00\x00")

func confDbYmlBytes() ([]byte, error) {
	return bindataRead(
		_confDbYml,
		"conf/db.yml",
	)
}

func confDbYml() (*asset, error) {
	bytes, err := confDbYmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "conf/db.yml", size: 529, mode: os.FileMode(438), modTime: time.Unix(1554776041, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"conf/app.yml": confAppYml,
	"conf/db.yml": confDbYml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"conf": &bintree{nil, map[string]*bintree{
		"app.yml": &bintree{confAppYml, map[string]*bintree{}},
		"db.yml": &bintree{confDbYml, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

